# application.yml
routing:
  osrm:
    base-url: http://router.project-osrm.org
    timeout: 30000
  nominatim:
    base-url: https://nominatim.openstreetmap.org
    timeout: 10000
  co2:
    factor: 0.120

spring:
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=1h